# Python Weekly Assignment

In [1]:
# Section A — Exception Handling

In [2]:
# 1. Write a function safe_divide(a, b) that divides two numbers and handles ZeroDivisionError and TypeError separately, printing an appropriate message for each. Use a finally block to print 'Operation attempted.' regardless of the outcome. Test it with valid numbers, division by zero, and a string input.
def safe_divide(a, b):
    try:
        print("Result =", a / b)

    except ZeroDivisionError:
        print("Cannot divide by zero!")

    except TypeError:
        print("Please enter numbers only!")

    finally:
        print("Operation attempted.")


# Valid division
safe_divide(10, 2)

# Division by zero
safe_divide(10, 0)

# String input
safe_divide("10", 2)

Result = 5.0
Operation attempted.
Cannot divide by zero!
Operation attempted.
Please enter numbers only!
Operation attempted.


In [8]:
# 2. Write a function validate_age(age) that raises a custom exception InvalidAgeError (a class you define, inheriting from Exception) if age is negative or greater than 120. Catch this exception in a calling block and print a user-friendly message. Test it with at least 3 different values.
class InvalidAgeError(Exception):
    def validate_age(age):
        if age < 0 or age > 120:
            raise InvalidAgeError
        print("Valid Age")
    try:
        validate_age(25)
        validate_age(-5)
        validate_age(150)

    except InvalidAgeError:
        print("Invalid age! Age should be between 0 and 120.")

Valid Age
Invalid age! Age should be between 0 and 120.


In [9]:
# 3. Write a program that repeatedly asks the user (use a loop with at least 3 simulated inputs in a list, e.g. user_inputs = ['10', 'abc', '0', '5']) to enter a number and divide 100 by it. Handle the following in a single try block using multiple except clauses:
#a) ValueError if the input is not a number.
#b) ZeroDivisionError if the input is zero.
#c) A generic Exception as a catch-all for anything else.
#Print the result if successful, otherwise print which error occurred.
user_inputs = ['10', 'abc', '0', '5']

for i in user_inputs:
    try:
        num = int(i)
        result = 100 / num
        print("Result =", result)

    except ValueError:
        print("ValueError: Input is not a number")

    except ZeroDivisionError:
        print("ZeroDivisionError: Cannot divide by zero")

    except Exception:
        print("Some other error occurred")

Result = 10.0
ValueError: Input is not a number
ZeroDivisionError: Cannot divide by zero
Result = 20.0


In [10]:
# Section B — NumPy

In [11]:
# 4. Create a 1D NumPy array of integers from 1 to 20. Perform the following:
# a) Reshape it into a 4x5 2D array.
# b) Print the sum of each row and each column.
# c) Extract all elements greater than 10 using boolean indexing.
# d) Replace all even numbers in the array with -1.
import numpy as np

# Create array from 1 to 20
a = np.arange(1, 21)

# a) Reshape into 4x5
b = a.reshape(4, 5)
print(b)

# b) Sum of rows and columns
print("Row Sum:")
print(b.sum(axis=1))

print("Column Sum:")
print(b.sum(axis=0))

# c) Elements greater than 10
print("Elements greater than 10:")
print(a[a > 10])

# d) Replace even numbers with -1
a[a % 2 == 0] = -1
print("After replacing even numbers:")
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Row Sum:
[15 40 65 90]
Column Sum:
[34 38 42 46 50]
Elements greater than 10:
[11 12 13 14 15 16 17 18 19 20]
After replacing even numbers:
[ 1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19 -1]


In [12]:
# 5. Create two NumPy arrays A and B as shown below and perform:
# A = np.array([[1, 2], [3, 4]]) B = np.array([[5, 6], [7, 8]])
# a) Element-wise addition, subtraction, and multiplication.
# b) Matrix multiplication using np.dot() or the @ operator.
# c) Transpose of A.
# d) The determinant and inverse of A using np.linalg.
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# a) Addition, Subtraction, Multiplication
print("Addition:")
print(A + B)

print("Subtraction:")
print(A - B)

print("Multiplication:")
print(A * B)

# b) Matrix Multiplication
print("Matrix Multiplication:")
print(np.dot(A, B))

# c) Transpose of A
print("Transpose of A:")
print(A.T)

# d) Determinant and Inverse of A
print("Determinant of A:")
print(np.linalg.det(A))

print("Inverse of A:")
print(np.linalg.inv(A))

Addition:
[[ 6  8]
 [10 12]]
Subtraction:
[[-4 -4]
 [-4 -4]]
Multiplication:
[[ 5 12]
 [21 32]]
Matrix Multiplication:
[[19 22]
 [43 50]]
Transpose of A:
[[1 3]
 [2 4]]
Determinant of A:
-2.0000000000000004
Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [13]:
# 6. Generate a NumPy array of 15 random integers between 1 and 100 using np.random.randint() (set a seed of 42 for reproducibility). Then:
# a) Find the mean, median, standard deviation, min, and max.
# b) Sort the array in descending order.
# c) Find the indices of the 3 largest values using np.argsort().
# d) Normalize the array so all values lie between 0 and 1.
import numpy as np

np.random.seed(42)

a = np.random.randint(1, 101, 15)

print("Array =", a)

# a) Mean, Median, Min, Max
print("Mean =", np.mean(a))
print("Median =", np.median(a))
print("Std =", np.std(a))
print("Min =", np.min(a))
print("Max =", np.max(a))

# b) Descending order
print(np.sort(a)[::-1])

# c) Indices of 3 largest values
print(np.argsort(a)[-3:])

# d) Normalize
b = (a - a.min()) / (a.max() - a.min())
print(b)

Array = [ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22]
Mean = 58.06666666666667
Median = 72.0
Std = 31.4843170836247
Min = 3
Max = 100
[100  93  88  87  83  75  75  72  61  52  24  22  21  15   3]
[10  1 11]
[0.50515464 0.92783505 0.12371134 0.71134021 0.59793814 0.18556701
 0.82474227 0.86597938 0.74226804 0.74226804 0.87628866 1.
 0.21649485 0.         0.19587629]


In [14]:
# Section C — Pandas Basics

In [15]:
# 7. Create a Pandas DataFrame from the dictionary below and perform the following: 
# data = { "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"], "Age": [23, 21, 25, 22, 24], "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"], "Score": [88, 92, 79, 95, 67], }
# a) Display the first 3 rows and the data types of each column.
# b) Add a new column Grade based on Score (>=90 'A', >=75 'B', else 'C').
# c) Sort the DataFrame by Score in descending order.
# d) Filter rows where Department is 'AI'.
import pandas as pd

data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}

df = pd.DataFrame(data)

# a) First 3 rows and data types
print(df.head(3))
print(df.dtypes)

# b) Add Grade column
df["Grade"] = ["B", "A", "B", "A", "C"]
print(df)

# c) Sort by Score
print(df.sort_values("Score", ascending=False))

# d) Department = AI
print(df[df["Department"] == "AI"])

    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
Name          object
Age            int64
Department    object
Score          int64
dtype: object
    Name  Age    Department  Score Grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C
    Name  Age    Department  Score Grade
3  Meera   22       Web Dev     95     A
1  Priya   21  Data Science     92     A
0  Aarav   23            AI     88     B
2  Karan   25            AI     79     B
4  Sahil   24  Data Science     67     C
    Name  Age Department  Score Grade
0  Aarav   23         AI     88     B
2  Karan   25         AI     79     B


In [16]:
# 8. Using the same DataFrame from Q7:
# a) Group by Department and find the average Score for each.
# b) Find the row with the highest Score using idxmax().
# c) Rename the column Score to Marks.
# d) Drop the Age column and display the resulting DataFrame.
import pandas as pd

data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}

df = pd.DataFrame(data)

# a) First 3 rows and data types
print(df.head(3))
print(df.dtypes)

# b) Add Grade column
df["Grade"] = ["B", "A", "B", "A", "C"]
print(df)

# c) Sort by Score
print(df.sort_values("Score", ascending=False))

# d) Department = AI
print(df[df["Department"] == "AI"])


    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
Name          object
Age            int64
Department    object
Score          int64
dtype: object
    Name  Age    Department  Score Grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C
    Name  Age    Department  Score Grade
3  Meera   22       Web Dev     95     A
1  Priya   21  Data Science     92     A
0  Aarav   23            AI     88     B
2  Karan   25            AI     79     B
4  Sahil   24  Data Science     67     C
    Name  Age Department  Score Grade
0  Aarav   23         AI     88     B
2  Karan   25         AI     79     B


In [18]:
# 9. Create a DataFrame with some missing values as shown below and handle them:
# import numpy as np data = { "Product": ["Pen", "Notebook", "Eraser", "Sharpener", "Ruler"], "Price": [10, np.nan, 5, 8, np.nan], "Stock": [100, 50, np.nan, 30, 20], }
# a) Check the number of missing values in each column using isnull().sum().
# b) Fill missing Price values with the column mean.
# c) Drop rows where Stock is still missing.
# d) Save the cleaned DataFrame to a CSV file named cleaned_products.csv without the index.
import pandas as pd
import numpy as np

data = {
    "Product": ["Pen", "Notebook", "Eraser", "Sharpener", "Ruler"],
    "Price": [10, np.nan, 5, 8, np.nan],
    "Stock": [100, 50, np.nan, 30, 20]
}

df = pd.DataFrame(data)

# Missing values
print(df.isnull().sum())

# Fill missing Price values with mean
df["Price"] = df["Price"].fillna(df["Price"].mean())

# Drop rows with missing Stock
df = df.dropna(subset=["Stock"])

# Save to CSV
df.to_csv("cleaned_products.csv", index=False)

print(df)

Product    0
Price      2
Stock      1
dtype: int64
     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0


In [19]:
# 10. Read the CSV file created in Q9 (cleaned_products.csv) back into a new DataFrame and:
# a) Print its shape and column names.
# b) Add a new column Total_Value as Price multiplied by Stock.
# c) Use describe() to print summary statistics of the numeric columns.
# d) Wrap the file reading step in a try-except block to handle the case where the file does not exist (FileNotFoundError).
import pandas as pd

try:
    # Read CSV file
    df = pd.read_csv("cleaned_products.csv")

    # a) Shape and column names
    print("Shape:", df.shape)
    print("Columns:", df.columns)

    # b) Add Total_Value column
    df["Total_Value"] = df["Price"] * df["Stock"]

    print(df)

    # c) Summary statistics
    print(df.describe())

except FileNotFoundError:
    print("File not found!")

Shape: (4, 3)
Columns: Index(['Product', 'Price', 'Stock'], dtype='object')
     Product      Price  Stock  Total_Value
0        Pen  10.000000  100.0  1000.000000
1   Notebook   7.666667   50.0   383.333333
2  Sharpener   8.000000   30.0   240.000000
3      Ruler   7.666667   20.0   153.333333
           Price       Stock  Total_Value
count   4.000000    4.000000     4.000000
mean    8.333333   50.000000   444.166667
std     1.122167   35.590261   382.500303
min     7.666667   20.000000   153.333333
25%     7.666667   27.500000   218.333333
50%     7.833333   40.000000   311.666667
75%     8.500000   62.500000   537.500000
max    10.000000  100.000000  1000.000000
