## Numpy

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [5]:
# creating Arrays

In [6]:
sample_array = np.array([1,2,3,4])

In [7]:
sample_array

array([1, 2, 3, 4])

In [8]:
sample_array2 = np.array([1,7,9,7])

In [9]:
sample_array2

array([1, 7, 9, 7])

In [10]:
# 2D Array (a Matrix) with 2 rows and 2 columns

In [11]:
sample_array_2 = np.array([[1,2],[3,4]])

In [13]:
sample_array_2

array([[1, 2],
       [3, 4]])

In [14]:
arr1 = np.array([[10,20],[30,45]])

In [15]:
arr1

array([[10, 20],
       [30, 45]])

In [16]:
#3D Tensor(2 Matrice, each with 2 rows and 2 columns)

In [17]:
sample_tensor_3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [18]:
sample_tensor_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
# Dimension

In [20]:
#0-D Array(Scalar) 5
#1-D Array (vector) [1,2,3,4]
#2-D Array (Matrix) (rows,cplumns)
#3-D Array (Tensor) (page,row,columns)

In [21]:
# Array properties

In [22]:
sample_array = np.array([[1,2,3],[4,5,6]])

In [23]:
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
# shape

In [26]:
sample_array.shape

(2, 3)

In [27]:
# dimensions

In [28]:
sample_array.ndim

2

In [29]:
# total elements

In [30]:
sample_array.size

6

In [31]:
# data type

In [33]:
sample_array.dtype

dtype('int64')

In [34]:
arr =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [37]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
arr.ndim

3

In [38]:
arr.shape

(2, 2, 3)

In [39]:
arr.size

12

In [40]:
arr.dtype

dtype('int64')

In [41]:
# special Arrays

In [42]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [47]:
np.arange(3,70,10)

array([ 3, 13, 23, 33, 43, 53, 63])

In [48]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [49]:
np.linspace(3,4,9)

array([3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ])

In [50]:
# Indexing & Slicing

In [51]:
sample_array = np.array([10,20,30,40])

In [52]:
sample_array

array([10, 20, 30, 40])

In [53]:
sample_array[0]

np.int64(10)

In [54]:
sample_array[2]

np.int64(30)

In [55]:
sample_array[-1]

np.int64(40)

In [56]:
# Slicing

In [57]:
sample_array[1:3]

array([20, 30])

In [ ]:
# Array Operations

In [6]:
import numpy as np

In [7]:
a=np.array([1,2,3])

In [8]:
b=np.array([4,5,6])

In [9]:
a

array([1, 2, 3])

In [10]:
b

array([4, 5, 6])

In [11]:
a+b

array([5, 7, 9])

In [12]:
a-b

array([-3, -3, -3])

In [13]:
a*b

array([ 4, 10, 18])

In [14]:
a/b

array([0.25, 0.4 , 0.5 ])

In [15]:
arr1=np.array([2,4,6])

In [16]:
arr2=np.array([1,3,5])

In [17]:
arr1

array([2, 4, 6])

In [18]:
arr2

array([1, 3, 5])

In [19]:
arr1+arr2

array([ 3,  7, 11])

In [20]:
arr1-arr2

array([1, 1, 1])

In [21]:
arr1*arr2

array([ 2, 12, 30])

In [25]:
arr1/arr2

array([2.        , 1.33333333, 1.2       ])

In [26]:
# Mathematical Functions

In [27]:
sample_array=np.array([1,4,9])

In [28]:
sample_array

array([1, 4, 9])

In [29]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [30]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [31]:
sample_array_2=np.array([100,400,900])

In [36]:
sample_array_3=np.array([10,40,90])

In [37]:
sample_array_2

array([100, 400, 900])

In [38]:
np.sqrt(sample_array_2)

array([10., 20., 30.])

In [39]:
np.exp(sample_array_3)

array([2.20264658e+04, 2.35385267e+17, 1.22040329e+39])

In [40]:
np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [41]:
# Statistical Functions

In [43]:
sample_array=np.array([1,2,3,4,5])

In [44]:
sample_array

array([1, 2, 3, 4, 5])

In [45]:
np.mean(sample_array)

np.float64(3.0)

In [46]:
np.median(sample_array)

np.float64(3.0)

In [47]:
np.std(sample_array)

np.float64(1.4142135623730951)

In [48]:
np.max(sample_array)

np.int64(5)

In [49]:
np.min(sample_array)

np.int64(1)

In [51]:
# Reshaping Arrays

In [54]:
a = np.arange(6)

In [55]:
a

array([0, 1, 2, 3, 4, 5])

In [56]:
reshaped=a.reshape(2,3)

In [57]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
# Array Flattened

In [60]:
sample_array=np.array([[1,2],[3,4]])

In [61]:
sample_array

array([[1, 2],
       [3, 4]])

In [62]:
sample_array.flatten()

array([1, 2, 3, 4])

In [65]:
sample_array_3=np.array([[[1,2],[3,4]],[[4,5],[7,8]]])

In [66]:
sample_array_3.flatten()

array([1, 2, 3, 4, 4, 5, 7, 8])

In [67]:
# Joining Arrays

In [69]:
a=np.array([1,2])

In [70]:
b=np.array([3,4])

In [72]:
np.concat((a,b))

array([1, 2, 3, 4])

In [73]:
# Splitting Arrays

In [74]:
sample_array=np.array([1,2,3,4])

In [75]:
sample_array

array([1, 2, 3, 4])

In [77]:
np.array_split(sample_array,2)

[array([1, 2]), array([3, 4])]

In [78]:
# Random Module

In [80]:
np.random.rand(3)

array([0.03958584, 0.86792669, 0.448923  ])

In [83]:
np.random.randint(1,10,5)

array([4, 1, 6, 4, 8], dtype=int32)

In [84]:
# Axis Concept

In [86]:
sample_array=np.array([[1,2],[3,4]])

In [87]:
sample_array

array([[1, 2],
       [3, 4]])

In [88]:
np.sum(sample_array,axis=0)

array([4, 6])

In [89]:
np.sum(sample_array,axis=1)

array([3, 7])

In [90]:
#NaN and Missing Values

In [91]:
sample_array=np.array([1,np.nan,3])

In [93]:
sample_array

array([ 1., nan,  3.])

In [94]:
np.isnan(sample_array)

array([False,  True, False])

In [95]:
# Create two numpy arrays and perform element wise addition, subtraction, multiplication and modulus operations

In [106]:
a=np.array([5,2,3])

In [107]:
b=np.array([4,8,6])

In [108]:
a

array([5, 2, 3])

In [109]:
b

array([4, 8, 6])

In [110]:
a+b

array([ 9, 10,  9])

In [111]:
a-b

array([ 1, -6, -3])

In [112]:
a*b

array([20, 16, 18])

In [113]:
a/b

array([1.25, 0.25, 0.5 ])

In [115]:
a%b

array([1, 2, 3])